version: '2'
services:

  proxy:
    image: nginx:latest
    ports:
        - "8200:80"
    links:
        - apollo
        - galaxy
        - tripal
        - ngadmin
        - chado_jb
        - jbrowse
        - postgrest
        - postgrest_tripal
        - postgraphql
    volumes:
        - "./nginx:/etc/nginx/conf.d"

  remoteuser:
    image: "quay.io/erasche/gx-cookie-proxy:latest"
    environment:
      GALAXY_DB_URL: "postgresql://postgres:postgres@db.postgres.rancher.internal:5432/postgres?client_encoding=utf8&sslmode=disable"
      GALAXY_SECRET: "?????"
      GXC_BACKEND_URL: "target:8080"
    links:
      - galaxy:galaxy
      - apollo:target

  galaxy:
    image: quay.io/erasche/docker-galaxy-annotation
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
        GALAXY_WEBAPOLLO_URL: "http://apollo:8080/apollo"
        GALAXY_WEBAPOLLO_EXT_URL: "/apollo"
        GALAXY_WEBAPOLLO_PASSWORD: "password"
        GALAXY_WEBAPOLLO_USER: admin@local.host
        GALAXY_SHARED_DIR: /apollo-data
        GALAXY_JBROWSE_SHARED_DIR: /jbrowse/data

  apollo:
    image: quay.io/erasche/apollo:remote_user
    links:
      - "apollo_db:db"
      - "tripal_db"
    environment:
      CONTEXT_PATH: "apollo"
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: postgres
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://tripal_db/postgres"
    volumes_from:
        - "galaxy:ro"

  apollo_db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: password

  postgrest:
    image: quay.io/erasche/postgrest:latest
    links:
      - "tripal_db:db"
    environment:
      POSTGREST_JWT_SECRET: thisisnotarealsecret
      POSTGREST_SCHEMA: chado
      PG_PASSWORD: postgres
      PG_DB: postgres

  postgrest_tripal:
    image: quay.io/erasche/postgrest:latest
    links:
      - "tripal_db:db"
    environment:
      POSTGREST_JWT_SECRET: thisisnotarealsecret
      POSTGREST_SCHEMA: public
      PG_PASSWORD: postgres
      PG_DB: postgres

  postgraphql:
    image: erasche/postgraphql:latest
    environment:
        DB_GRAPHQL_PATH: "/graphql"
        DB_GRAPHIQL_PATH: "/graphiql"
        PG_SECRET: "deadbeefcafe"
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: db
        PGPORT: 5432
        PGDATABASE: postgres
        DB_SCHEMA: "public"
    links:
        - "tripal_db:db"

  postgraphql-refseqs:
    build: refseqs
    ports:
      - "9997:5000"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
    links:
      - "tripal_db:db"

  pgadmin4:
    image: thajeztah/pgadmin4
    links:
      - "tripal_db:db"

  ngadmin:
    image: quay.io/erasche/chado-angular-admin:latest
    links:
      - "postgrest"
      - "postgrest_tripal"
    ports:
      - "8400:80"

  chado_jb:
    image: quay.io/erasche/chado-jbrowse-connector:latest
    environment:
      POSTGRES_PASSWORD: postgres
      SITE_PATH: "http://localhost:8200/jbrowse/"
      JBROWSE: "http://localhost:8200/jbrowse_actual/"
    links:
      - "tripal_db:db"
    ports:
      - "8500:8500"

  tripal_db:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      - POSTGRES_PASSWORD=postgres
        # The default chado image would try to install the schema on first run,
        # we just want the tools to be available.
      - INSTALL_CHADO_SCHEMA=0
    volumes:
      - /var/lib/postgresql/data/

  tripal:
    image: quay.io/erasche/tripal:latest
    links:
      - tripal_db:postgres
    volumes:
      - /var/www/html/sites
      - /var/www/private
    environment:
      UPLOAD_LIMIT: 20M
      MEMORY_LIMIT: 128M
      TRIPAL_GIT_CLONE_MODULES: "https://github.com/abretaud/tripal_rest_api.git"
      TRIPAL_ENABLE_MODULES: "tripal_rest_api"
    #ports:
      #- "8080:80"

  jbrowse:
    image: erasche/jbrowse:1.12.0
    volumes_from:
        - "galaxy:ro"
    ports:
        - "80"
